#
# Quarkus
#
quarkus:
  artemis:
    url: tcp://localhost:61616
  datasource:
    jdbc:
      url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;INIT=runscript from 'classpath:h2-init.sql'"
  log:
    console:
      enable: false
    file:
      enable: true
      path: target/test.log
